# Generated by Django 4.2.5 on 2023-10-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
