# Generated by Django 4.2.5 on 2023-10-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_statistic_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roulette'),
        ),
    ]
