# Generated by Django 4.2.5 on 2023-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='is_operative',
            field=models.BooleanField(default=True),
        ),
    ]
